# params config

iter:
    batch_size:    5000
    epoch:         20
    model_dir:     '../docs/model/checkpoints/'
    model_name:    'adios_best.h5'
    model_type:    'CNN-non-static' # only CNN-static, CNN-non-static, CNN-rand valiable
X:
    embedding_dim: 100
Conv1D:
    layer1:
        filters:       128
        filter_size:   [3,4,5]
        pooling_size:  3 # default 2
    # layer2:
    #   filters:       128
    #   filter_size:   [3,4,5]
    #   pooling_size:  3 # default 2
H:
    dropout:       0.3
    # batch_norm: {beta_initializer: zeros}
H0:
    dim:           256
    dropout:       0.3
    batch_norm: {momentum: 0.9}
H1:
    dim:         256
    dropout:     0.3
    batch_norm: {momentum: 0.9}
Y0:
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
    batch_norm: {momentum: 0.9}
Y1:
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
    batch_norm: {momentum: 0.9}
