# params config

iter:
    batch_size:    2000
    epoch:         10
    model_dir:     '../docs/model/checkpoints/'
    model_name:    'adios_best.h5'
    model_type:    'CNN-non-static' # only CNN-static, CNN-non-static, CNN-rand valiable
X:
    embedding_dim: 100
Conv1D:
    filters:       128
    filter_size:   [3,4,5]
    pooling_size:  3 # default 2
H:
    dropout:       0.3
    # batch_norm: {beta_initializer: ones}
H0:
    dim:           256
    dropout:       0.3
    # batch_norm: {beta_initializer: ones}
# H1:
#     dim:         256
#     dropout:     0.3
    # batch_norm: {beta_initializer: zeros}
Y0:
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
    # batch_norm: {beta_initializer: ones}
Y1:
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
