# params config

iter:
    batch_size: 1000
    epoch:  5
    model_dir:  '../docs/model/checkpoints/'
    model_name: 'adios_best.h5'
    model_type: 'CNN-non-static' # only CNN-static, CNN-non-static, CNN-rand valiable
X:
    embedding_dim: 100
Conv1D:
    filters:    64
    filter_size:  [3,4,5]
    pooling_size: 3 # default 2
H:
    dropout:    0.3
    batch_norm: {beta_initializer: zeros}
H0:
    dim:        200
    dropout:    0.3
    batch_norm: {beta_initializer: zeros}
# H1:
#     dim:        64
#     dropout:    0.3
#     batch_norm: {beta_initializer: zeros}
Y0:
    W_regularizer: 0.001
    activity_reg: {l1: 0.001}
    batch_norm: {beta_initializer: zeros}
Y1:
    W_regularizer: 0.001
    activity_reg: {l1: 0.001}
