# params config

voc_size: 0 # just placeholder
pos_size: 0 # just placeholder
embed_size: 50

batch_size:    128
epoch:         3
learning_rate:    0.01
log_train_every:  10
log_eval_every: 30
model_dir:     '../docs/model/'
model_name:   'best'
gpu_fraction: 0.45

words:
    dim: 0  # just placeholder
    RNN:
      cell: 48
      drop_out: 0.2
      rnn_drop_out: 0.1
#      batch_norm: 0.9

pos:
    dim: 0  # just placeholder
    RNN:
      cell: 48
      drop_out: 0.2
      rnn_drop_out: 0.1
#      batch_norm: 0.9

H:
    dim:           64
    dropout:       0.3
    batch_norm: {momentum: 0.9}
Y0:
    dim:  3
    loss_weight:    0.4
    activate_func:  'sigmoid'
    loss_func:  'binary_crossentropy'
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
    batch_norm: {momentum: 0.9}
Y1:
    dim:  6
    loss_weight:    0.6
    activate_func:  'sigmoid'
    loss_func:  'binary_crossentropy'
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
    batch_norm: {momentum: 0.9}
